set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv)

set(TOOLCHAIN_PATH "C:/progs/wch-gcc-12")
set(TOOLCHAIN_PATH_BIN "${TOOLCHAIN_PATH}/bin")
set(MY_TOOLCHAIN_CROSS_PREFIX "riscv-wch-elf-")

if (CMAKE_HOST_WIN32)
    # detect the host win32 and not the target win32:
    # https://stackoverflow.com/a/70382484/4535300
    # the variable CMAKE_EXECUTABLE_SUFFIX will get
    # overriden when calling project, so use the
    # CMAKE_HOST_EXECUTABLE_SUFFIX instead
    set(CMAKE_HOST_EXECUTABLE_SUFFIX ".exe")
else()
    set(CMAKE_HOST_EXECUTABLE_SUFFIX "")
endif()

set(CMAKE_C_COMPILER   "${TOOLCHAIN_PATH_BIN}/${MY_TOOLCHAIN_CROSS_PREFIX}gcc${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PATH_BIN}/${MY_TOOLCHAIN_CROSS_PREFIX}g++${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_SIZE         "${TOOLCHAIN_PATH_BIN}/${MY_TOOLCHAIN_CROSS_PREFIX}size${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_OBJCOPY      "${TOOLCHAIN_PATH_BIN}/${MY_TOOLCHAIN_CROSS_PREFIX}objcopy${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_OBJDUMP      "${TOOLCHAIN_PATH_BIN}/${MY_TOOLCHAIN_CROSS_PREFIX}objdump${CMAKE_HOST_EXECUTABLE_SUFFIX}")
set(CMAKE_STRIP        "${TOOLCHAIN_PATH_BIN}/${MY_TOOLCHAIN_CROSS_PREFIX}strip${CMAKE_HOST_EXECUTABLE_SUFFIX}")
