//
// Created by anton on 12/01/2025.
//

#pragma once

// Make sure your build scripts `touch` this file on each compilation so they
// are retrigered each time to refresh the date/time before the build.

// In our cmake this is labeled as autogenerated to achieve the same

namespace firmwareBuildInfo {
    static const auto date = __DATE__;
    static const auto time = __TIME__;
}
